### PR TITLE
Add upper bound evaluation

### PR DESCRIPTION
**Pull request by alex-schutz**
Adds upper bound calculation from POMDP by using Q-learning and treating it like an MDP.

## To do:
- [x] Update bounds method to pass tuning parameters
- [x] Add tests

### CODE REVIEW

**Comment by alex-schutz** [comment]
@yangyou95 It's not complete yet, but is this the right track?

**Comment by yangyou95** [comment]
> @yangyou95 It's not complete yet, but is this the right track? How should we set the hyperparameters for Q-learning (hard code or pass as input arguments?)

Hi Alex, thanks for the update. Yes, and we should set hyperparameters as input arguments. For Q-learning, the parameters should be:  
- nb_sim (number of simulations)
- learning_rate 
- sim_depth (if we want to solve a finite-horizon problem, I think it could be useful in CTP settings)

**Comment by alex-schutz** [comment]
> Hi Alex, we should not add or change functions in the "PomdpInterface" if there are no bugs. We should directly use the step function provided in the 'SimInterface'.

Okay, I can update that. I'm just a bit confused because the `SimInterface` step function is for the multi-agent problem, so we are choosing an action in the multi agent space, but I thought we only want the upper bound of a single agent POMDP? Or should there be some additional information so we can work out which action we are choosing in the multi agent space?

We'll also need to add `GetSizeOfS` to `SimInterface`.

**Comment by yangyou95** [comment]
> > Hi Alex, we should not add or change functions in the "PomdpInterface" if there are no bugs. We should directly use the step function provided in the 'SimInterface'.
> 
> Okay, I can update that. I'm just a bit confused because the `SimInterface` step function is for the multi-agent problem, so we are choosing an action in the multi agent space, but I thought we only want the upper bound of a single agent POMDP? Or should there be some additional information so we can work out which action we are choosing in the multi agent space?
> 
> We'll also need to add `GetSizeOfS` to `SimInterface`.

Hi Alex, I understand your concerns now. The step function in "SimInterface" in MCJESP can be used both in Dec-POMDPs and POMDPs. The inputs and outputs of this step function are indices but not actual "actions" or "observations". For Dec-POMDP, after we call the step function, we can decompose the joint action index or joint observation index to local ones.

**Pull request merged**
